class Type:
    def __init__(self, mime: str, extension: str) -> None: ...
    @property
    def mime(self) -> str: ...
    @property
    def extension(self) -> str: ...
    def is_extension(self, extension: str) -> bool: ...
    def is_mime(self, mime: str) -> bool: ...
    def match(self, buf: bytes | bytearray | memoryview) -> bool: ...
