from pathlib import PurePath
from typing import Any

from .types import Type

types: list[Type]

def guess(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> Type | None: ...
def guess_mime(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> str | None: ...
def guess_extension(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> str | None: ...
def get_type(mime: str | None = ..., ext: str | None = ...) -> Type | None: ...
def add_type(instance: Type) -> None: ...
