from pathlib import PurePath
from typing import Any

def is_extension_supported(ext: str) -> bool: ...
def is_mime_supported(mime: str) -> bool: ...
def is_image(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
def is_archive(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
def is_audio(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
def is_video(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
def is_font(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
def is_document(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bool: ...
