from pathlib import PurePath
from typing import Any, Sequence

from .types import Type

InputType = str | bytes | bytearray | memoryview | PurePath | Any

def match(
    obj: InputType,
    matchers: Sequence[Type] = ...,
) -> Type | None: ...
def image_match(obj: InputType) -> Type | None: ...
def font_match(obj: InputType) -> Type | None: ...
def video_match(obj: InputType) -> Type | None: ...
def audio_match(obj: InputType) -> Type | None: ...
def archive_match(obj: InputType) -> Type | None: ...
def application_match(obj: InputType) -> Type | None: ...
def document_match(obj: InputType) -> Type | None: ...
