from pathlib import PurePath
from typing import Any

def get_signature_bytes(path: str | PurePath) -> bytearray: ...
def signature(array: bytes | bytearray | memoryview) -> bytearray: ...
def get_bytes(obj: str | bytes | bytearray | memoryview | PurePath | Any) -> bytearray: ...
